sonar.projectKey=trananhtai2204205-beep_PetCare
sonar.organization=trananhtai2204205-beep
sonar.projectName=PetCare
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/assets/plugins/**,**/assets/js/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
